// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psgbhbtxdoabyrtwlamg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZ2JoYnR4ZG9hYnlydHdsYW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NzA0NzMsImV4cCI6MjA0OTQ0NjQ3M30.L1emFM90fjXr8cAFwsVKzqJ20_f_FyB_YHGMhRHo8Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);